# Generated by Django 3.0.8 on 2021-04-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_auto_20210427_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productimage',
        ),
    ]
