# Generated by Django 3.2 on 2021-04-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_auto_20210427_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image1',
            field=models.ImageField(blank=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image2',
            field=models.ImageField(blank=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image3',
            field=models.ImageField(blank=True, upload_to='products/images/'),
        ),
    ]
