# Generated by Django 3.2 on 2021-04-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_auto_20210427_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image1',
            field=models.ImageField(blank=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image2',
            field=models.ImageField(blank=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image3',
            field=models.ImageField(blank=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/'),
        ),
    ]
